<?php

namespace App\Services\Explainability;

use App\Models\AiImprovementSignal;
use App\Models\AiResultReview;
use App\Models\User;
use App\Services\AiService;
use App\Services\AnalysisPayloadCache;
use App\Services\AuditLogService;
use App\Services\Explainability\Explainers\AiGradingExplainer;
use App\Services\Explainability\Explainers\AssessmentQualityExplainer;
use App\Services\Explainability\Explainers\CoPoMappingExplainer;
use App\Services\Explainability\Explainers\GeneratedQuestionExplainer;
use App\Services\Explainability\Explainers\InterGraderExplainer;
use App\Services\Explainability\Explainers\LoAlignmentExplainer;
use App\Services\Explainability\Explainers\QuestionLabelExplainer;
use App\Services\Explainability\Explainers\RagAnswerExplainer;
use App\Services\Explainability\Explainers\RecommendationExplainer;
use App\Services\Explainability\Explainers\RubricExplainer;
use App\Services\Explainability\Explainers\SimilarityExplainer;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

/**
 * STEP 45 entry point: explain / review / override / audit any AI result by (type, id).
 *
 * - Explanations are built from stored results + existing rules (deterministic); nothing is generated by an LLM.
 * - Authorization is delegated to the explainer (course ability via CourseAccessService, or ownership for chat).
 * - Reviews never modify AI columns; overrides only write faculty-controlled fields and are recorded + audited.
 */
class ExplanationService
{
    /** @var array<string, AbstractExplainer> */
    protected array $explainers = [];

    public function __construct(protected AuditLogService $audit, protected EvaluationStatusResolver $evaluation, protected AiService $ai)
    {
    }

    public function explainer(string $type): AbstractExplainer
    {
        $type = strtolower(trim($type));
        if (!in_array($type, config('ai_explainability.result_types', []), true)) {
            throw new ExplainabilityException("Unknown AI result type '{$type}'.", 404);
        }
        return $this->explainers[$type] ??= match ($type) {
            'question_type', 'difficulty', 'bloom', 'topic' => new QuestionLabelExplainer($type, $this->ai),
            'lo_alignment' => app(LoAlignmentExplainer::class),
            'similarity' => app(SimilarityExplainer::class),
            'assessment_quality' => app(AssessmentQualityExplainer::class),
            'recommendation' => app(RecommendationExplainer::class),
            'rubric' => app(RubricExplainer::class),
            'generated_question' => app(GeneratedQuestionExplainer::class),
            'rag_answer' => app(RagAnswerExplainer::class),
            'ai_grading' => app(AiGradingExplainer::class),
            'co_po_mapping' => app(CoPoMappingExplainer::class),
            'inter_grader' => app(InterGraderExplainer::class),
        };
    }

    /** @return array{0: AbstractExplainer, 1: Model} */
    public function resolve(User $user, string $type, int $id, bool $forReview = false): array
    {
        $explainer = $this->explainer($type);
        $target = $explainer->find($id);
        if (!$target) {
            throw new ExplainabilityException('AI result not found.', 404);
        }
        if (!$explainer->canView($user, $target)) {
            throw new ExplainabilityException('Unauthorized access to this AI result.', 403);
        }
        if ($forReview && !$explainer->canReview($user, $target)) {
            throw new ExplainabilityException('You are not allowed to review this AI result.', 403);
        }
        return [$explainer, $target];
    }

    public function explain(User $user, string $type, int $id, bool $logView = true): array
    {
        [$explainer, $target] = $this->resolve($user, $type, $id);
        $type = $explainer->type();

        $builder = $explainer->explain($user, $target, new ExplanationBuilder($type, $id));
        $data = $builder->evaluation($this->evaluation->resolve($type))->toArray();

        $reviews = AiResultReview::where('ai_result_type', $type)->where('ai_result_id', $id)->orderByDesc('id')->get();
        $latest = $reviews->first();
        $data['review']['history_count'] = $reviews->count();
        $data['review']['latest'] = $latest ? $this->reviewPayload($latest) : null;
        $data['review']['can_review'] = $explainer->canReview($user, $target);
        $data['review']['override_reasons'] = collect(config('ai_explainability.override_reasons', []))->map(fn ($label, $code) => ['code' => $code, 'label' => $label])->values()->all();
        $data['review']['actions'] = $data['review']['can_review'] ? $data['review']['actions'] : [];
        $data['method']['label'] = $this->methodLabel($data['method']['type']);

        if ($logView) {
            $this->audit->log('AI_EXPLANATION_VIEWED', $target, $id, $this->auditMeta($type, $id, $explainer, $target, ['evidence_count' => count($data['evidence'])]), $user);
        }

        return $data;
    }

    public function review(User $user, string $type, int $id, string $action, ?string $comment = null): array
    {
        $action = strtoupper($action);
        if (!in_array($action, config('ai_explainability.review_actions', []), true)) {
            throw new ExplainabilityException('Invalid review action.', 422);
        }
        [$explainer, $target] = $this->resolve($user, $type, $id, true);
        $type = $explainer->type();

        return DB::transaction(function () use ($user, $type, $id, $action, $comment, $explainer, $target) {
            $review = AiResultReview::create([
                'user_id' => $user->id, 'ai_result_type' => $type, 'ai_result_id' => $id, 'action' => $action,
                'ai_value' => $explainer->aiValue($target), 'comment' => $comment,
                'analysis_report_id' => $explainer->analysisReportId($target), 'course_id' => $explainer->course($target)?->id,
                'explanation_version' => config('ai_explainability.explanation_version'),
            ]);
            $explainer->afterReview($user, $target, $action, $comment);
            $this->signal($user, $type, $id, $action, $explainer, $target, ['comment_present' => $comment !== null]);
            $this->audit->log("AI_RESULT_{$action}", $target, $id, $this->auditMeta($type, $id, $explainer, $target, ['review_id' => $review->id]), $user);
            $this->forgetCaches($explainer, $target);

            return ['review' => $this->reviewPayload($review)];
        });
    }

    public function override(User $user, string $type, int $id, array $value, string $reason, ?string $comment = null): array
    {
        $reason = strtoupper($reason);
        if (!array_key_exists($reason, config('ai_explainability.override_reasons', []))) {
            throw new ExplainabilityException('Invalid override reason.', 422);
        }
        [$explainer, $target] = $this->resolve($user, $type, $id, true);
        $type = $explainer->type();
        if ($explainer->overrideOptions($target) === []) {
            throw new ExplainabilityException('This AI result cannot be overridden here.', 422);
        }

        return DB::transaction(function () use ($user, $type, $id, $value, $reason, $comment, $explainer, $target) {
            $aiValue = $explainer->aiValue($target);
            $applied = $explainer->applyOverride($user, $target, $value);
            $review = AiResultReview::create([
                'user_id' => $user->id, 'ai_result_type' => $type, 'ai_result_id' => $id, 'action' => AiResultReview::ACTION_OVERRIDDEN,
                'ai_value' => $aiValue, 'override_value' => $applied, 'override_reason' => $reason, 'comment' => $comment,
                'analysis_report_id' => $explainer->analysisReportId($target), 'course_id' => $explainer->course($target)?->id,
                'explanation_version' => config('ai_explainability.explanation_version'),
            ]);
            $this->signal($user, $type, $id, 'OVERRIDDEN', $explainer, $target, ['override_reason' => $reason]);
            $this->audit->log('AI_RESULT_OVERRIDDEN', $target, $id, $this->auditMeta($type, $id, $explainer, $target, ['review_id' => $review->id, 'override_reason' => $reason, 'override_value' => $applied]), $user);
            $this->forgetCaches($explainer, $target);

            return ['review' => $this->reviewPayload($review), 'applied' => $applied];
        });
    }

    /** Client-reported view events (result viewed / evidence expanded / source opened). */
    public function recordEvent(User $user, string $type, int $id, string $action, array $meta = []): void
    {
        $action = strtoupper($action);
        if (!in_array($action, config('ai_explainability.view_events', []), true)) {
            throw new ExplainabilityException('Unsupported explainability event.', 422);
        }
        [$explainer, $target] = $this->resolve($user, $type, $id);
        $safeMeta = array_intersect_key($meta, array_flip(['level', 'evidence_type', 'document_id', 'chunk_id', 'source_id']));
        $this->audit->log($action, $target, $id, $this->auditMeta($explainer->type(), $id, $explainer, $target, $safeMeta), $user);
    }

    public function history(User $user, string $type, int $id): array
    {
        [$explainer] = $this->resolve($user, $type, $id);
        return AiResultReview::with('user:id,name')->where('ai_result_type', $explainer->type())->where('ai_result_id', $id)->orderByDesc('id')->get()
            ->map(fn ($r) => $this->reviewPayload($r))->all();
    }

    protected function signal(User $user, string $type, int $id, string $action, AbstractExplainer $explainer, Model $target, array $meta): void
    {
        AiImprovementSignal::create([
            'user_id' => $user->id,
            'recommendation_id' => $type === 'recommendation' ? $id : null,
            'analysis_report_id' => $explainer->analysisReportId($target),
            'assessment_id' => $this->assessmentIdOf($target),
            'signal_type' => "AI_RESULT_{$action}",
            'signal_value' => match ($action) { 'ACCEPTED' => 'positive', 'REJECTED', 'OVERRIDDEN' => 'negative', default => 'neutral' },
            'source' => 'explainability',
            'metadata' => array_merge(['ai_result_type' => $type, 'ai_result_id' => $id, 'explanation_version' => config('ai_explainability.explanation_version')], $meta),
        ]);
    }

    protected function forgetCaches(AbstractExplainer $explainer, Model $target): void
    {
        $assessmentId = $this->assessmentIdOf($target);
        if ($assessmentId) {
            AnalysisPayloadCache::forget($assessmentId);
        }
    }

    /** Best-effort assessment id for cache invalidation and improvement signals (null when not assessment-scoped). */
    protected function assessmentIdOf(Model $target): ?int
    {
        $id = $target->getAttribute('assessment_id')
            ?? $target->analysisReport?->assessment_id
            ?? $target->question?->assessment_id
            ?? $target->currentQuestion?->assessment_id
            ?? $target->studentAnswer?->submission?->assessment_id;
        return $id !== null ? (int) $id : null;
    }

    protected function auditMeta(string $type, int $id, AbstractExplainer $explainer, Model $target, array $extra = []): array
    {
        return array_merge([
            'ai_result_type' => $type, 'ai_result_id' => $id,
            'analysis_report_id' => $explainer->analysisReportId($target),
            'course_id' => $explainer->course($target)?->id,
            'explanation_version' => config('ai_explainability.explanation_version'),
        ], $extra);
    }

    protected function reviewPayload(AiResultReview $r): array
    {
        return [
            'id' => $r->id, 'action' => $r->action, 'override_value' => $r->override_value, 'override_reason' => $r->override_reason,
            'override_reason_label' => $r->override_reason ? config("ai_explainability.override_reasons.{$r->override_reason}") : null,
            'comment' => $r->comment, 'ai_value' => $r->ai_value, 'analysis_report_id' => $r->analysis_report_id,
            'user' => $r->relationLoaded('user') && $r->user ? ['id' => $r->user->id, 'name' => $r->user->name] : ['id' => $r->user_id],
            'created_at' => $r->created_at?->toIso8601String(),
        ];
    }

    protected function methodLabel(string $type): string
    {
        return match ($type) {
            'RULE_BASED' => 'FacultyLens deterministic rules',
            'MODEL_BASED' => 'AI classification model',
            'EMBEDDING_BASED' => 'Embedding-based semantic comparison',
            'HYBRID' => 'Hybrid AI + FacultyLens rules',
            'GENERATIVE' => 'Generative AI (validated)',
            'HUMAN_CONFIRMED' => 'Faculty confirmed',
            default => $type,
        };
    }
}
