import React from 'react';
import { ReportFilter, ReportMetadata } from '@/types/report';
import { SCOPE_LABELS } from './ReportScopeSelector';

const when = (iso: string | null | undefined): string => (iso ? new Date(iso).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' }) : 'N/A');

export const filtersToText = (filters: ReportFilter | null | undefined): string => {
  const entries = Object.entries(filters ?? {}).filter(([, v]) => v !== undefined && v !== null && v !== '');
  return entries.length ? entries.map(([k, v]) => `${k.replace(/_/g, ' ')}: ${v}`).join(' · ') : 'None';
};

interface ReportMetadataProps {
  metadata?: ReportMetadata | null;
  /** For generated reports (history) where the full metadata block isn't stored. */
  fallback?: {
    report_label: string;
    scope_type: ReportMetadata['scope'];
    filters: ReportFilter;
    generated_by?: string | null;
    generated_at?: string | null;
    data_as_of?: string | null;
    assessment?: string | null;
    assessment_version?: string | null;
    course?: string | null;
    academic_year?: string | null;
    semester?: string | null;
  };
  recordCount?: number | null;
}

/** Every report identifies FacultyLens, type, generator, timestamps, scope, filters and version. */
export const ReportMetadataPanel: React.FC<ReportMetadataProps> = ({ metadata, fallback, recordCount }) => {
  const rows: [string, string][] = metadata
    ? [
        ['Report Type', metadata.report_label],
        ['Scope', `${SCOPE_LABELS[metadata.scope]} — ${metadata.scope_description}`],
        ['Filters', filtersToText(metadata.filters)],
        ['Course', metadata.course ? `${metadata.course.code} — ${metadata.course.name}` : 'N/A'],
        ['Assessment', metadata.assessment?.title ?? 'N/A'],
        ['Assessment Version', metadata.assessment_version?.version_label ?? 'N/A'],
        ['Academic Year / Semester', `${metadata.academic_year ?? 'N/A'} / ${metadata.semester ?? 'N/A'}`],
        ['Data Period', metadata.data_period ?? 'All available data'],
        ['Generated By', metadata.generated_by.name],
        ['Generated At', when(metadata.generated_at)],
        ['Data As Of', when(metadata.data_as_of)],
        ['Records', recordCount === undefined || recordCount === null ? 'N/A' : String(recordCount)],
      ]
    : fallback
      ? [
          ['Report Type', fallback.report_label],
          ['Scope', SCOPE_LABELS[fallback.scope_type]],
          ['Filters', filtersToText(fallback.filters)],
          ['Course', fallback.course ?? 'N/A'],
          ['Assessment', fallback.assessment ?? 'N/A'],
          ['Assessment Version', fallback.assessment_version ?? 'N/A'],
          ['Academic Year / Semester', `${fallback.academic_year ?? 'N/A'} / ${fallback.semester ?? 'N/A'}`],
          ['Generated By', fallback.generated_by ?? 'N/A'],
          ['Generated At', when(fallback.generated_at)],
          ['Data As Of', when(fallback.data_as_of)],
          ['Records', recordCount === undefined || recordCount === null ? 'N/A' : String(recordCount)],
        ]
      : [];
  if (!rows.length) return null;

  return (
    <section className="rounded-xl border border-sage-200 bg-white p-4" data-testid="report-metadata">
      <div className="flex items-center justify-between mb-2">
        <h3 className="text-sm font-semibold text-sage-800">Report Metadata</h3>
        <span className="text-[11px] text-sage-400">Generated from FacultyLens</span>
      </div>
      <dl className="grid grid-cols-1 sm:grid-cols-2 gap-x-6 gap-y-1.5">
        {rows.map(([k, v]) => (
          <div key={k} className="flex gap-2 text-xs">
            <dt className="w-40 shrink-0 text-sage-500">{k}</dt>
            <dd className="text-sage-800 break-words min-w-0">{v}</dd>
          </div>
        ))}
      </dl>
    </section>
  );
};
