<?php

namespace App\Services\Explainability\Explainers;

use App\Models\Course;
use App\Models\Recommendation;
use App\Models\User;
use App\Services\Explainability\AbstractExplainer;
use App\Services\Explainability\ExplainabilityException;
use App\Services\Explainability\ExplanationBuilder;
use App\Services\Explainability\ExplanationValidator;
use App\Services\RecommendationFeedbackService;
use Illuminate\Database\Eloquent\Model;

/** Recommendation: issue → why → evidence → source traceability (STEP 45 §16–17). Review reuses STEP 20 feedback. */
class RecommendationExplainer extends AbstractExplainer
{
    protected const SOURCE_BY_CATEGORY = [
        'topic_coverage' => ['Topic Coverage Analysis', 'topic_coverage'],
        'learning_outcome' => ['Learning Outcome Alignment', 'learning_outcome_coverage'],
        'difficulty' => ['Difficulty Analysis', 'difficulty_distribution'],
        'cognitive_level' => ['Cognitive Level Analysis', 'cognitive_diversity'],
        'question_diversity' => ['Question Format Analysis', 'question_diversity'],
        'marks_distribution' => ['Marks Distribution Analysis', 'marks_distribution'],
        'semantic_similarity' => ['Semantic Similarity Analysis', 'similarity_matches'],
        'assessment_quality' => ['Assessment Quality Engine', 'overall_quality_score'],
    ];

    public function __construct(protected ExplanationValidator $validator, protected RecommendationFeedbackService $feedback)
    {
    }

    public function type(): string
    {
        return 'recommendation';
    }

    public function find(int $id): ?Model
    {
        return Recommendation::with(['analysisReport.assessment.course', 'feedback'])->find($id);
    }

    public function course(Model $target): ?Course
    {
        return $target->analysisReport?->assessment?->course;
    }

    public function reviewAbility(): ?string
    {
        return 'approve_recommendation';
    }

    public function analysisReportId(Model $target): ?int
    {
        return $target->analysis_report_id;
    }

    public function aiValue(Model $target): array
    {
        return ['problem' => $target->problem, 'priority' => $target->priority, 'category' => $target->category, 'status' => $target->status];
    }

    public function afterReview(User $user, Model $target, string $action, ?string $comment): void
    {
        $decision = match ($action) {
            'ACCEPTED' => 'ACCEPTED',
            'REJECTED' => 'DISMISSED',
            default => 'REVIEWED',
        };
        try {
            $this->feedback->submitFeedback($target, $user, ['decision' => $decision, 'comment' => $comment, 'reason' => 'EXPLAINABILITY_REVIEW']);
        } catch (\Exception $e) {
            throw new ExplainabilityException($e->getMessage(), 403);
        }
    }

    public function explain(User $user, Model $target, ExplanationBuilder $b): ExplanationBuilder
    {
        /** @var Recommendation $rec */
        $rec = $target;
        $report = $rec->analysisReport;
        [$sourceName, $metric] = self::SOURCE_BY_CATEGORY[strtolower((string) $rec->category)] ?? ['Assessment Analysis', $rec->category];
        $evidence = is_array($rec->evidence) ? $rec->evidence : ($rec->evidence ? [$rec->evidence] : []);
        $numbers = [];
        foreach ($evidence as $line) {
            $text = is_scalar($line) ? (string) $line : json_encode($line);
            if (preg_match_all('/\d+(?:\.\d+)?/', $text, $m)) {
                foreach ($m[0] as $n) {
                    $numbers[] = (float) $n;
                }
            }
        }
        $fallback = 'FacultyLens detected that ' . lcfirst(rtrim((string) $rec->problem, '.')) . ', based on the ' . strtolower($sourceName) . ' of this assessment. This may warrant faculty review.';
        $why = $rec->explanation ? $this->validator->validatedOrFallback($rec->explanation, $numbers ? ['allowed_numbers' => $numbers] : [], $fallback) : ['text' => $fallback, 'validated' => false, 'fallback_used' => true];

        $b->result(strtoupper((string) $rec->priority), null, $rec->problem ?: $rec->title, ['priority' => strtoupper((string) $rec->priority), 'category' => $rec->category, 'status' => $rec->status])
            ->summary($why['text'])
            ->detail('Issue', $rec->problem ?: $rec->title)
            ->detail('Suggested consideration', $this->soften($rec->recommendation ?: $rec->description))
            ->detail('Source', $sourceName)
            ->detail('Metric', $metric)
            ->detail('Source metric (as stored)', $rec->source_metric)
            ->detail('Threshold', 'Configured FacultyLens thresholds / blueprint targets')
            ->detail('Generated by', 'FacultyLens Recommendation Engine v1 (rule-based)');
        $n = 0;
        foreach ($evidence as $key => $line) {
            $n++;
            $label = is_string($key) ? ucfirst(str_replace('_', ' ', $key)) : "Evidence {$n}";
            $b->evidence(['type' => 'metric', 'label' => $label, 'text' => is_scalar($line) ? (string) $line : json_encode($line)]);
        }
        if ($evidence === []) {
            $b->evidenceStatus('none', 'This recommendation did not record structured evidence.');
        }

        return $b->method('RULE_BASED', 'Problem detector compares analysis metrics with configured thresholds and blueprint targets; each finding becomes a recommendation with its evidence.', ['Problem detector', 'Recommendation generator', 'Configured thresholds'])
            ->model(['name' => 'facultylens-recommendation-engine', 'version' => '1.0.0'])
            ->confidence(null, 'Deterministic rule — no model confidence applies.')
            ->analysisContext($report?->id, $report?->analysis_version, $report?->is_current)
            ->limitations($this->limitations('recommendation'))
            ->link('View underlying analysis', 'analysis', $report?->assessment_id, ['analysis_report_id' => $report?->id, 'section' => $metric])
            ->review(['overridable' => false, 'actions' => ['ACCEPTED', 'REJECTED', 'REVIEWED'], 'reject_label' => 'Dismiss', 'faculty_value' => $rec->status, 'faculty_notes' => $rec->faculty_notes]);
    }

    protected function soften(?string $text): ?string
    {
        if ($text === null) {
            return null;
        }
        return preg_replace(['/\byou must\b/i', '/\byour assessment is wrong\b/i', '/\bstudents will fail\b/i'], ['consider', 'this assessment may need review', 'students may struggle'], $text);
    }
}
