import React from 'react';
import { AlertTriangle, CheckCircle2, CircleSlash, FileQuestion, ShieldAlert, Sparkles, UserCheck } from 'lucide-react';
import { Badge, BadgeVariant } from './Badge';

/**
 * STEP 46: Shared AI-safety UI vocabulary.
 *
 * AiOriginBadge   — who is responsible for a value: AI Suggested / Faculty Approved / Faculty Final.
 * AiSafetyState   — evidence / availability states: Insufficient evidence, Conflicting evidence,
 *                   Source unavailable, AI analysis unavailable, Faculty review recommended.
 * AiSuggestionNotice — the one-line "AI-generated suggestion — verify before use" reminder.
 *
 * These never compute anything; they only render states the backend has already decided.
 */

export type AiOrigin = 'AI_SUGGESTED' | 'FACULTY_APPROVED' | 'FACULTY_FINAL';

export const AI_ORIGIN_LABELS: Record<AiOrigin, string> = {
  AI_SUGGESTED: 'AI Suggested',
  FACULTY_APPROVED: 'Faculty Approved',
  FACULTY_FINAL: 'Faculty Final',
};

const ORIGIN_VARIANT: Record<AiOrigin, BadgeVariant> = {
  AI_SUGGESTED: 'Pending',
  FACULTY_APPROVED: 'Good',
  FACULTY_FINAL: 'Analyzed',
};

export const AiOriginBadge: React.FC<{ origin: AiOrigin; className?: string }> = ({ origin, className }) => (
  <Badge variant={ORIGIN_VARIANT[origin]} className={className} data-testid={`ai-origin-${origin.toLowerCase()}`} title={originTitle(origin)}>
    {origin === 'AI_SUGGESTED' ? <Sparkles className="w-3 h-3" aria-hidden /> : <UserCheck className="w-3 h-3" aria-hidden />}
    {AI_ORIGIN_LABELS[origin]}
  </Badge>
);

function originTitle(origin: AiOrigin): string {
  switch (origin) {
    case 'AI_SUGGESTED':
      return 'Generated by AI. Not an academic decision — faculty must review before use.';
    case 'FACULTY_APPROVED':
      return 'Reviewed and approved by faculty.';
    case 'FACULTY_FINAL':
      return 'Final value recorded by faculty.';
  }
}

export type AiSafetyStateKind =
  | 'INSUFFICIENT_EVIDENCE'
  | 'CONFLICTING_EVIDENCE'
  | 'SOURCE_UNAVAILABLE'
  | 'AI_UNAVAILABLE'
  | 'FACULTY_REVIEW_RECOMMENDED'
  | 'GROUNDED';

export const AI_SAFETY_STATE_LABELS: Record<AiSafetyStateKind, string> = {
  INSUFFICIENT_EVIDENCE: 'Insufficient evidence',
  CONFLICTING_EVIDENCE: 'Conflicting evidence',
  SOURCE_UNAVAILABLE: 'Source unavailable',
  AI_UNAVAILABLE: 'AI analysis unavailable',
  FACULTY_REVIEW_RECOMMENDED: 'Faculty review recommended',
  GROUNDED: 'Grounded in documents',
};

const STATE_VARIANT: Record<AiSafetyStateKind, BadgeVariant> = {
  INSUFFICIENT_EVIDENCE: 'Attention',
  CONFLICTING_EVIDENCE: 'Critical',
  SOURCE_UNAVAILABLE: 'neutral',
  AI_UNAVAILABLE: 'neutral',
  FACULTY_REVIEW_RECOMMENDED: 'Attention',
  GROUNDED: 'Good',
};

const STATE_ICON: Record<AiSafetyStateKind, React.ReactNode> = {
  INSUFFICIENT_EVIDENCE: <FileQuestion className="w-3 h-3" aria-hidden />,
  CONFLICTING_EVIDENCE: <ShieldAlert className="w-3 h-3" aria-hidden />,
  SOURCE_UNAVAILABLE: <CircleSlash className="w-3 h-3" aria-hidden />,
  AI_UNAVAILABLE: <CircleSlash className="w-3 h-3" aria-hidden />,
  FACULTY_REVIEW_RECOMMENDED: <AlertTriangle className="w-3 h-3" aria-hidden />,
  GROUNDED: <CheckCircle2 className="w-3 h-3" aria-hidden />,
};

export const AiSafetyState: React.FC<{ state: AiSafetyStateKind; className?: string; children?: React.ReactNode; 'data-testid'?: string }> = ({ state, className, children, ...rest }) => (
  <Badge variant={STATE_VARIANT[state]} className={className} data-testid={rest['data-testid'] ?? `ai-safety-${state.toLowerCase()}`} data-safety-state={state}>
    {STATE_ICON[state]}
    {children ?? AI_SAFETY_STATE_LABELS[state]}
  </Badge>
);

/** Map the backend chat evidence_status (+grounded fallback) onto a UI state. */
export function chatEvidenceState(evidenceStatus: string | null | undefined, grounded: boolean): AiSafetyStateKind {
  switch ((evidenceStatus || '').toUpperCase()) {
    case 'CONFLICTING':
      return 'CONFLICTING_EVIDENCE';
    case 'SUFFICIENT':
      return grounded ? 'GROUNDED' : 'INSUFFICIENT_EVIDENCE';
    case 'INSUFFICIENT':
      return 'INSUFFICIENT_EVIDENCE';
    default:
      return grounded ? 'GROUNDED' : 'INSUFFICIENT_EVIDENCE';
  }
}

export const AI_SUGGESTION_NOTICE = 'AI-generated suggestion — verify before use.';

export const AiSuggestionNotice: React.FC<{ className?: string; text?: string }> = ({ className, text = AI_SUGGESTION_NOTICE }) => (
  <p className={['text-xs text-sage-500 dark:text-sage-400 flex items-center gap-1.5', className].filter(Boolean).join(' ')} data-testid="ai-suggestion-notice" role="note">
    <Sparkles className="w-3 h-3 text-amber-500" aria-hidden />
    {text}
  </p>
);

/** Confidence display rule: only a validated number in [0,1] is shown; anything else is "Confidence unavailable". */
export function formatConfidence(value: unknown): string {
  if (typeof value !== 'number' || Number.isNaN(value) || value < 0 || value > 1) return 'Confidence unavailable';
  return `${Math.round(value * 100)}% (model-reported, not accuracy)`;
}
