<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>FacultyLens — {{ $doc['metadata']['report_label'] }}</title>
<style>
  @page { margin: 28px 28px 54px 28px; }
  body { font-family: DejaVu Sans, Helvetica, sans-serif; font-size: 9.5px; color: #1E261D; margin: 0; }
  h1 { font-size: 18px; margin: 0 0 2px; color: #2F3E2E; }
  h2 { font-size: 12px; margin: 16px 0 5px; border-bottom: 1px solid #C3CBB9; padding-bottom: 3px; color: #2F3E2E; page-break-after: avoid; }
  .muted { color: #5A6B52; } .brand { font-size: 10px; color: #8C9A82; letter-spacing: .04em; text-transform: uppercase; }
  .note { background: #F3F4EE; border: 1px solid #E8ECE3; padding: 6px 8px; margin: 8px 0; }
  .warn { background: #FEF3C7; border: 1px solid #FDE68A; padding: 6px 8px; margin: 8px 0; }
  table { width: 100%; border-collapse: collapse; margin-top: 4px; page-break-inside: auto; } tr { page-break-inside: avoid; }
  th, td { border: 1px solid #E8ECE3; padding: 3px 5px; text-align: left; vertical-align: top; word-wrap: break-word; } th { background: #F3F4EE; font-weight: bold; }
  .meta td { border: none; padding: 1px 6px 1px 0; } .meta th { border: none; background: none; padding: 1px 8px 1px 0; color: #5A6B52; font-weight: normal; white-space: nowrap; }
  .kpi { display: inline-block; width: 23%; border: 1px solid #E8ECE3; padding: 5px 6px; margin: 0 1% 6px 0; vertical-align: top; background: #fff; } .kpi b { display: block; font-size: 12px; color: #2F3E2E; }
  .footer { position: fixed; bottom: -40px; left: 0; right: 0; font-size: 8px; color: #5A6B52; border-top: 1px solid #E8ECE3; padding-top: 4px; }
  .pagenum:before { content: counter(page); }
</style>
</head>
<body>
@php
  $m = $doc['metadata'];
  $fmt = function ($v) { if ($v === null || $v === '') return 'N/A'; if (is_bool($v)) return $v ? 'Yes' : 'No'; if (is_array($v)) return implode('; ', array_map(fn ($x) => is_scalar($x) ? (string) $x : json_encode($x), $v)); return (string) $v; };
  $when = fn ($iso) => $iso ? \Illuminate\Support\Carbon::parse($iso)->format('F j, Y g:i A') : 'N/A';
@endphp
<div class="footer">
  @foreach(explode("\n", $footer) as $line)<div>{{ $line }}</div>@endforeach
  <div>Generated from FacultyLens · {{ $when($m['generated_at']) }} · Page <span class="pagenum"></span></div>
</div>

<div class="brand">FacultyLens · Institutional Report</div>
<h1>{{ $m['report_label'] }}</h1>
<p class="muted" style="margin:0 0 8px">{{ $m['scope_description'] }}</p>

<table class="meta">
  <tr><th>Report Type</th><td>{{ $m['report_type'] }}</td><th>Generated By</th><td>{{ $m['generated_by']['name'] ?? 'N/A' }}{{ !empty($m['generated_by']['department']) ? ' · ' . $m['generated_by']['department'] : '' }}</td></tr>
  <tr><th>Scope</th><td>{{ $m['scope'] }}</td><th>Generated At</th><td>{{ $when($m['generated_at']) }}</td></tr>
  <tr><th>Assessment</th><td>{{ $m['assessment']['title'] ?? 'N/A' }}</td><th>Data As Of</th><td>{{ $when($m['data_as_of']) }}</td></tr>
  <tr><th>Assessment Version</th><td>{{ $m['assessment_version']['version_label'] ?? 'N/A' }}</td><th>Academic Year / Semester</th><td>{{ $fmt($m['academic_year']) }} / {{ $fmt($m['semester']) }}</td></tr>
  <tr><th>Data Period</th><td>{{ $fmt($m['data_period']) }}</td><th>Filters</th><td>{{ empty($m['filters']) ? 'None' : collect($m['filters'])->map(fn ($v, $k) => "$k=$v")->implode(', ') }}</td></tr>
</table>

@if(!empty($doc['warnings']))
  <div class="warn"><b>Notes</b><ul style="margin:4px 0 0 14px;padding:0">@foreach($doc['warnings'] as $w)<li>{{ $w }}</li>@endforeach</ul></div>
@endif

@if(!empty($doc['summary']))
<h2>Summary</h2>
@foreach($doc['summary'] as $kv)
  <div class="kpi"><span class="muted">{{ $kv['label'] }}</span><b>{{ $fmt($kv['value']) }}</b></div>
@endforeach
<div style="clear:both"></div>
@endif

@foreach($doc['sections'] as $s)
  <h2>{{ $s['title'] }}</h2>
  @if(!empty($s['description']))<p class="muted">{{ $s['description'] }}</p>@endif
  @if(!empty($s['text']))<div class="note">{{ $s['text'] }}</div>@endif
  @if(!empty($s['items']))<table class="meta">@foreach($s['items'] as $it)<tr><th>{{ $it['label'] }}</th><td>{{ $fmt($it['value']) }}</td></tr>@endforeach</table>@endif
@endforeach

@foreach($doc['tables'] as $t)
  <h2>{{ $t['title'] }}</h2>
  @if(count($t['rows']) === 0)
    <p class="muted">No data available.</p>
  @else
    <table>
      <thead><tr>@foreach($t['columns'] as $c)<th>{{ $c['label'] }}</th>@endforeach</tr></thead>
      <tbody>
      @foreach($t['rows'] as $row)
        <tr>@foreach($t['columns'] as $c)<td>{{ $fmt($row[$c['key']] ?? null) }}</td>@endforeach</tr>
      @endforeach
      </tbody>
    </table>
    @if(!empty($t['truncated']))<p class="muted">{{ $t['truncated'] }} more row(s) omitted from the PDF. Export CSV or XLSX for the complete dataset.</p>@endif
  @endif
  @if(!empty($t['note']))<p class="muted">{{ $t['note'] }}</p>@endif
@endforeach
</body>
</html>
