import {
  User,
  Course,
  Assessment,
  AssessmentAnalysis,
  HistoryRecord,
  DashboardStats,
} from '../types';

export const mockCurrentUser: User = {
  id: 'usr-001',
  name: 'Dr. Tariqul Islam',
  fullName: 'Dr. Tariqul Islam',
  email: 'tariqul.islam@university.edu',
  department: 'Computer Science and Engineering',
  designation: 'Associate Professor',
  role: 'faculty',
  avatarUrl: '',
  createdAt: '2024-01-15',
};

export const mockDashboardStats: DashboardStats = {
  totalCourses: 5,
  totalAssessments: 18,
  analysesCompleted: 14,
  recommendationsCount: 27,
  averageQualityScore: 84.5,
  activeSemester: 'Spring 2026',
};

export const mockCourses: Course[] = [
  {
    id: 'course-1',
    code: 'CSE 3201',
    title: 'Database Systems',
    semester: 'Spring 2026',
    year: 2026,
    section: 'A & B',
    creditHours: 3.0,
    department: 'Computer Science & Engineering',
    studentsCount: 84,
    assessmentCount: 4,
    learningOutcomesCount: 5,
    learningOutcomes: [
      { id: 'clo-1', code: 'CLO-1', description: 'Design conceptual and logical relational data models using ER and relational diagrams.', bloomLevel: 'Apply' },
      { id: 'clo-2', code: 'CLO-2', description: 'Formulate complex queries using Relational Algebra and structured SQL.', bloomLevel: 'Apply' },
      { id: 'clo-3', code: 'CLO-3', description: 'Evaluate schema designs and apply normalization rules (1NF to BCNF) to reduce redundancy.', bloomLevel: 'Evaluate' },
      { id: 'clo-4', code: 'CLO-4', description: 'Analyze concurrency control protocols and crash recovery algorithms in transactional systems.', bloomLevel: 'Analyze' },
      { id: 'clo-5', code: 'CLO-5', description: 'Implement indexing and query optimization strategies for performance tuning.', bloomLevel: 'Create' },
    ],
    createdAt: '2026-01-05',
    updatedAt: '2026-02-14',
  },
  {
    id: 'course-2',
    code: 'CSE 3202',
    title: 'Computer Networks',
    semester: 'Spring 2026',
    year: 2026,
    section: 'A',
    creditHours: 3.0,
    department: 'Computer Science & Engineering',
    studentsCount: 46,
    assessmentCount: 3,
    learningOutcomesCount: 4,
    learningOutcomes: [
      { id: 'clo-201', code: 'CLO-1', description: 'Explain layered network architectures and protocol suites (OSI and TCP/IP).', bloomLevel: 'Understand' },
      { id: 'clo-202', code: 'CLO-2', description: 'Calculate IP subnetting, routing tables, and analyze Dijkstra/Bellman-Ford algorithms.', bloomLevel: 'Apply' },
      { id: 'clo-203', code: 'CLO-3', description: 'Analyze transport layer flow control, congestion control, and TCP reliability mechanisms.', bloomLevel: 'Analyze' },
      { id: 'clo-204', code: 'CLO-4', description: 'Evaluate socket programming applications and network security protocols.', bloomLevel: 'Evaluate' },
    ],
    createdAt: '2026-01-05',
    updatedAt: '2026-02-10',
  },
  {
    id: 'course-3',
    code: 'CSE 3203',
    title: 'Software Engineering',
    semester: 'Spring 2026',
    year: 2026,
    section: 'B',
    creditHours: 3.0,
    department: 'Computer Science & Engineering',
    studentsCount: 42,
    assessmentCount: 4,
    learningOutcomesCount: 5,
    learningOutcomes: [
      { id: 'clo-301', code: 'CLO-1', description: 'Analyze software requirements and specify use cases following IEEE standards.', bloomLevel: 'Analyze' },
      { id: 'clo-302', code: 'CLO-2', description: 'Design modular architectures using UML diagrams and GoF design patterns.', bloomLevel: 'Create' },
      { id: 'clo-303', code: 'CLO-3', description: 'Apply Agile Scrum methodology with automated CI/CD workflows.', bloomLevel: 'Apply' },
      { id: 'clo-304', code: 'CLO-4', description: 'Formulate comprehensive unit and integration test strategies.', bloomLevel: 'Evaluate' },
    ],
    createdAt: '2026-01-06',
    updatedAt: '2026-02-18',
  },
  {
    id: 'course-4',
    code: 'CSE 2101',
    title: 'Data Structures and Algorithms',
    semester: 'Spring 2026',
    year: 2026,
    section: 'C',
    creditHours: 3.0,
    department: 'Computer Science & Engineering',
    studentsCount: 92,
    assessmentCount: 4,
    learningOutcomesCount: 5,
    learningOutcomes: [
      { id: 'clo-401', code: 'CLO-1', description: 'Demonstrate asymptotic time and space complexity analysis using Big-O notation.', bloomLevel: 'Understand' },
      { id: 'clo-402', code: 'CLO-2', description: 'Implement non-linear data structures including AVL trees, heaps, and graphs.', bloomLevel: 'Apply' },
      { id: 'clo-403', code: 'CLO-3', description: 'Design dynamic programming and greedy solutions for combinatorial problems.', bloomLevel: 'Create' },
    ],
    createdAt: '2026-01-08',
    updatedAt: '2026-02-15',
  },
  {
    id: 'course-5',
    code: 'CSE 4101',
    title: 'Distributed Systems',
    semester: 'Spring 2026',
    year: 2026,
    section: 'A',
    creditHours: 3.0,
    department: 'Computer Science & Engineering',
    studentsCount: 38,
    assessmentCount: 3,
    learningOutcomesCount: 4,
    learningOutcomes: [
      { id: 'clo-501', code: 'CLO-1', description: 'Assess consistency models, CAP theorem, and distributed consensus (Raft/Paxos).', bloomLevel: 'Evaluate' },
      { id: 'clo-502', code: 'CLO-2', description: 'Design fault-tolerant microservice architectures with RPC and message queues.', bloomLevel: 'Create' },
    ],
    createdAt: '2026-01-10',
    updatedAt: '2026-02-20',
  },
];

export const mockAssessments: Assessment[] = [
  {
    id: 'asm-1',
    courseId: 'course-1',
    courseCode: 'CSE 3201',
    courseTitle: 'Database Systems',
    title: 'CSE 3201 Midterm Examination',
    type: 'Midterm',
    semester: 'Spring 2026',
    status: 'Analyzed',
    qualityScore: 86,
    totalQuestions: 8,
    totalMarks: 50,
    uploadedAt: '2026-02-15',
    lastAnalyzedAt: '2026-02-15 14:32',
  },
  {
    id: 'asm-2',
    courseId: 'course-1',
    courseCode: 'CSE 3201',
    courseTitle: 'Database Systems',
    title: 'CSE 3201 Final Examination Draft',
    type: 'Final',
    semester: 'Spring 2026',
    status: 'Pending',
    totalQuestions: 10,
    totalMarks: 100,
    uploadedAt: '2026-02-22',
  },
  {
    id: 'asm-3',
    courseId: 'course-2',
    courseCode: 'CSE 3202',
    courseTitle: 'Computer Networks',
    title: 'CSE 3202 Midterm Exam',
    type: 'Midterm',
    semester: 'Spring 2026',
    status: 'Analyzed',
    qualityScore: 91,
    totalQuestions: 7,
    totalMarks: 40,
    uploadedAt: '2026-02-18',
    lastAnalyzedAt: '2026-02-18 09:15',
  },
  {
    id: 'asm-4',
    courseId: 'course-3',
    courseCode: 'CSE 3203',
    courseTitle: 'Software Engineering',
    title: 'CSE 3203 Midterm Assessment',
    type: 'Midterm',
    semester: 'Spring 2026',
    status: 'Analyzed',
    qualityScore: 78,
    totalQuestions: 6,
    totalMarks: 50,
    uploadedAt: '2026-02-19',
    lastAnalyzedAt: '2026-02-19 16:45',
  },
  {
    id: 'asm-5',
    courseId: 'course-4',
    courseCode: 'CSE 2101',
    courseTitle: 'Data Structures and Algorithms',
    title: 'CSE 2101 Quiz #2 (Graph Algorithms)',
    type: 'Quiz',
    semester: 'Spring 2026',
    status: 'Analyzed',
    qualityScore: 94,
    totalQuestions: 5,
    totalMarks: 20,
    uploadedAt: '2026-02-20',
    lastAnalyzedAt: '2026-02-20 11:10',
  },
  {
    id: 'asm-6',
    courseId: 'course-5',
    courseCode: 'CSE 4101',
    courseTitle: 'Distributed Systems',
    title: 'CSE 4101 Midterm Term Paper',
    type: 'Midterm',
    semester: 'Spring 2026',
    status: 'Needs Review',
    qualityScore: 68,
    totalQuestions: 6,
    totalMarks: 40,
    uploadedAt: '2026-02-21',
    lastAnalyzedAt: '2026-02-21 18:20',
  },
];

export const mockDetailedAnalysis: AssessmentAnalysis = {
  id: 'ana-001',
  assessmentId: 'asm-1',
  courseCode: 'CSE 3201',
  courseTitle: 'Database Systems',
  assessmentTitle: 'CSE 3201 Midterm Examination',
  semester: 'Spring 2026',
  analysisDate: '2026-02-15 14:32',
  status: 'Analyzed',
  metrics: {
    overallQualityScore: 86,
    topicCoverageScore: 89,
    learningOutcomeScore: 84,
    difficultyBalanceScore: 85,
    similarQuestionsCount: 2,
    totalQuestions: 8,
    totalMarks: 50,
  },
  difficultyDistribution: {
    easyPercent: 20,
    mediumPercent: 60,
    hardPercent: 20,
  },
  cognitiveDistribution: {
    lowerOrderPercent: 25,
    mediumOrderPercent: 55,
    higherOrderPercent: 20,
  },
  topicCoverages: [
    { topic: 'Relational Model & ER Diagrams', coveragePercent: 92, questionCount: 2, weightPercent: 25, status: 'Good' },
    { topic: 'Relational Algebra & SQL', coveragePercent: 95, questionCount: 3, weightPercent: 35, status: 'Good' },
    { topic: 'Database Normalization (1NF-BCNF)', coveragePercent: 88, questionCount: 2, weightPercent: 30, status: 'Good' },
    { topic: 'Transaction Basics & ACID', coveragePercent: 40, questionCount: 1, weightPercent: 10, status: 'Attention' },
  ],
  findings: [
    {
      id: 'fnd-1',
      title: 'Strong Normalization & SQL Coverage',
      description: 'The assessment provides comprehensive coverage of relational algebra and database normalization techniques with rigorous multi-table queries.',
      severity: 'Good',
      category: 'coverage',
    },
    {
      id: 'fnd-2',
      title: 'Learning Outcome 4 Has Low Question Coverage',
      description: 'CLO-4 (Transaction ACID properties and basic concurrency control) is represented by only one 5-mark question, falling below the recommended 15% curriculum allocation.',
      severity: 'Attention',
      category: 'alignment',
      relatedOutcome: 'CLO-4',
    },
    {
      id: 'fnd-3',
      title: 'Two Questions Highly Similar to Previous Assessments',
      description: 'Question 3 (SQL Subqueries) and Question 7 (B-Tree vs Hash Indexing) share >82% lexical and conceptual similarity with the Spring 2025 Midterm paper.',
      severity: 'Critical',
      category: 'similarity',
      relatedQuestions: [3, 7],
    },
    {
      id: 'fnd-4',
      title: 'Balanced Difficulty Distribution',
      description: 'The overall distribution follows academic best practices: 20% foundational (Easy), 60% standard application (Medium), and 20% analytical/evaluative (Hard).',
      severity: 'Good',
      category: 'difficulty',
    },
  ],
  recommendations: [
    {
      id: 'rec-1',
      title: 'Add at least one question targeting Learning Outcome 4',
      description: 'Incorporate a scenario-based question testing ACID transaction conflict serializability to fulfill CLO-4 requirements before final approval.',
      action: 'Add CLO-4 Question',
      priority: 'High',
      category: 'Learning Outcome',
    },
    {
      id: 'rec-2',
      title: 'Consider replacing Question 7 due to high historical similarity',
      description: 'Question 7 is 87% similar to Spring 2025 Midterm Q5. Replace with a distinct problem assessing index structure selectivity.',
      action: 'Replace Question 7',
      priority: 'High',
      category: 'Question Design',
    },
    {
      id: 'rec-3',
      title: 'Increase higher-order questions in the normalization topic',
      description: 'Consider converting Question 4 from standard functional dependency decomposition to an open synthesis scenario comparing 3NF vs BCNF trade-offs in write-heavy systems.',
      action: 'Elevate Cognitive Level',
      priority: 'Medium',
      category: 'Difficulty',
    },
  ],
  questions: [
    {
      id: 'q-1',
      questionNumber: 1,
      text: 'Explain the difference between total and partial participation in an Entity-Relationship model with a concrete university domain example.',
      maxMarks: 5,
      topic: 'Relational Model & ER Diagrams',
      learningOutcomeCode: 'CLO-1',
      cognitiveLevel: 'Understand',
      difficulty: 'Easy',
    },
    {
      id: 'q-2',
      questionNumber: 2,
      text: 'Given the schema for University Enrollment, construct relational algebra expressions to retrieve students who have registered for all courses offered by CSE department.',
      maxMarks: 7,
      topic: 'Relational Algebra & SQL',
      learningOutcomeCode: 'CLO-2',
      cognitiveLevel: 'Apply',
      difficulty: 'Medium',
    },
    {
      id: 'q-3',
      questionNumber: 3,
      text: 'Write an optimized SQL query utilizing window functions to find the top 2 highest scoring students per department.',
      maxMarks: 8,
      topic: 'Relational Algebra & SQL',
      learningOutcomeCode: 'CLO-2',
      cognitiveLevel: 'Apply',
      difficulty: 'Medium',
      similarityFlag: {
        isSimilar: true,
        matchedAssessment: 'CSE 3201 Spring 2025 Midterm (Q4)',
        similarityScore: 84,
        notes: 'Identical schema and window ranking structure with minor variable rename.',
      },
    },
    {
      id: 'q-4',
      questionNumber: 4,
      text: 'Given relation R(A, B, C, D, E) and functional dependencies F = {A->BC, CD->E, B->D, E->A}, determine the candidate keys and prove whether R is in 3NF and BCNF.',
      maxMarks: 8,
      topic: 'Database Normalization (1NF-BCNF)',
      learningOutcomeCode: 'CLO-3',
      cognitiveLevel: 'Analyze',
      difficulty: 'Hard',
    },
    {
      id: 'q-5',
      questionNumber: 5,
      text: 'Decompose relation S(P, Q, R, S, T) with dependencies into lossless-join, dependency-preserving BCNF relations.',
      maxMarks: 7,
      topic: 'Database Normalization (1NF-BCNF)',
      learningOutcomeCode: 'CLO-3',
      cognitiveLevel: 'Apply',
      difficulty: 'Medium',
    },
    {
      id: 'q-6',
      questionNumber: 6,
      text: 'Illustrate how a dirty read anomaly occurs under Read Uncommitted isolation level and explain how Strict 2PL prevents it.',
      maxMarks: 5,
      topic: 'Transaction Basics & ACID',
      learningOutcomeCode: 'CLO-4',
      cognitiveLevel: 'Understand',
      difficulty: 'Medium',
    },
    {
      id: 'q-7',
      questionNumber: 7,
      text: 'Compare the search time complexity of B+ Tree index versus Hash index for range query operations on indexed column Salary.',
      maxMarks: 5,
      topic: 'Database Normalization (1NF-BCNF)',
      learningOutcomeCode: 'CLO-3',
      cognitiveLevel: 'Understand',
      difficulty: 'Easy',
      similarityFlag: {
        isSimilar: true,
        matchedAssessment: 'CSE 3201 Spring 2025 Midterm (Q5)',
        similarityScore: 87,
        notes: 'Standard theoretical question verbatim repeated across two consecutive academic years.',
      },
    },
    {
      id: 'q-8',
      questionNumber: 8,
      text: 'Design a physical database indexing strategy for an e-commerce order table with 10M rows to support fast customer lookups and monthly analytical aggregation.',
      maxMarks: 5,
      topic: 'Relational Algebra & SQL',
      learningOutcomeCode: 'CLO-5',
      cognitiveLevel: 'Evaluate',
      difficulty: 'Hard',
    },
  ],
  summaryNote: 'Assessment is strong in technical depth and normalization concepts. Addressing CLO-4 coverage gap and swapping repeated question #7 will ensure full accreditation compliance.',
};

export const mockHistoryRecords: HistoryRecord[] = [
  {
    id: 'hist-1',
    assessmentId: 'asm-1',
    assessmentTitle: 'CSE 3201 Midterm Examination',
    courseCode: 'CSE 3201',
    courseTitle: 'Database Systems',
    qualityScore: 86,
    analysisDate: '2026-02-15 14:32',
    status: 'Analyzed',
    topicCoverageScore: 89,
    outcomeAlignmentScore: 84,
    similarQuestionsCount: 2,
  },
  {
    id: 'hist-2',
    assessmentId: 'asm-3',
    assessmentTitle: 'CSE 3202 Midterm Exam',
    courseCode: 'CSE 3202',
    courseTitle: 'Computer Networks',
    qualityScore: 91,
    analysisDate: '2026-02-18 09:15',
    status: 'Analyzed',
    topicCoverageScore: 94,
    outcomeAlignmentScore: 92,
    similarQuestionsCount: 0,
  },
  {
    id: 'hist-3',
    assessmentId: 'asm-4',
    assessmentTitle: 'CSE 3203 Midterm Assessment',
    courseCode: 'CSE 3203',
    courseTitle: 'Software Engineering',
    qualityScore: 78,
    analysisDate: '2026-02-19 16:45',
    status: 'Analyzed',
    topicCoverageScore: 81,
    outcomeAlignmentScore: 76,
    similarQuestionsCount: 3,
  },
  {
    id: 'hist-4',
    assessmentId: 'asm-5',
    assessmentTitle: 'CSE 2101 Quiz #2 (Graph Algorithms)',
    courseCode: 'CSE 2101',
    courseTitle: 'Data Structures and Algorithms',
    qualityScore: 94,
    analysisDate: '2026-02-20 11:10',
    status: 'Analyzed',
    topicCoverageScore: 96,
    outcomeAlignmentScore: 95,
    similarQuestionsCount: 0,
  },
  {
    id: 'hist-5',
    assessmentId: 'asm-6',
    assessmentTitle: 'CSE 4101 Midterm Term Paper',
    courseCode: 'CSE 4101',
    courseTitle: 'Distributed Systems',
    qualityScore: 68,
    analysisDate: '2026-02-21 18:20',
    status: 'Needs Review',
    topicCoverageScore: 70,
    outcomeAlignmentScore: 65,
    similarQuestionsCount: 4,
  },
  {
    id: 'hist-6',
    assessmentId: 'asm-7',
    assessmentTitle: 'CSE 3201 Quiz #1 (Relational Algebra)',
    courseCode: 'CSE 3201',
    courseTitle: 'Database Systems',
    qualityScore: 90,
    analysisDate: '2026-01-28 10:00',
    status: 'Analyzed',
    topicCoverageScore: 92,
    outcomeAlignmentScore: 89,
    similarQuestionsCount: 1,
  },
];

